import Vue from 'vue';
import Vuetify, {
  VApp,
  VAppBar,
  VAppBarNavIcon,
  VBtn,
  VCard,
  VCardActions,
  VCardText,
  VCardTitle,
  VContainer,
  VContent,
  VDatePicker,
  VDivider,
  VFlex,
  VFooter,
  VForm,
  VIcon,
  VImg,
  VLayout,
  VList,
  VListGroup,
  VListItem,
  VListItemAction,
  VListItemContent,
  VListItemSubtitle,
  VListItemTitle,
  VMenu,
  VSnackbar,
  VTab,
  VTabs,
  VTabItem,
  VTextField,
  VTextarea,
  VToolbar,
  VToolbarTitle,
  VToolbarItems,
  VTooltip,
} from 'vuetify/lib';
import theme from '../vuetify/theme';
import 'vuetify/dist/vuetify.min.css';

Vue.use(Vuetify);
export default new Vuetify({
  theme,
  components: {
    VApp,
    VContent,
    VToolbar,
    VToolbarTitle,
    VFooter,
    VContainer,
    VLayout,
    VFlex,
    VIcon,
    VMenu,
    VList,
    VListItem,
    VListItemTitle,
    VListItemSubtitle,
    VListItemContent,
    VListItemAction,
    VListGroup,
    VDatePicker,
    VBtn,
    VCard,
    VCardTitle,
    VCardText,
    VCardActions,
    VDivider,
    VTextField,
    VTextarea,
    VForm,
    VSnackbar,
    VImg,
  },
});
