name: Docker Image CI

on:
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: npm install
    - name: Build service
      run: npm run build
    - name: Build the Docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nouvelle0epoch/lne-front
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
